#!/usr/bin/env bash

source ~/.config/theming/brown

cat<<EOF
/* === Generated by generate-swaync-theme.sh === */

* {
    font-family: Fira Sans, sans-serif;
    font-size: 14px;
    color: ${COLOR_TEXT_PRIMARY};
}

#window {
    background-color: ${COLOR_BG};
    border: 2px solid ${COLOR_BORDER};
    border-radius: 8px;
    padding: 10px;
}

.notification {
    background-color: ${COLOR_BG_ALT};
    border: 1px solid ${COLOR_BORDER};
    border-radius: 6px;
    margin: 5px 0;
    padding: 8px;
    box-shadow: 0 0 10px ${COLOR_SHADOW};
}

.notification.critical {
    border-left: 4px solid ${COLOR_RED};
}

.notification.low {
    border-left: 4px solid ${COLOR_GREEN};
}

.notification.normal {
    border-left: 4px solid ${COLOR_ACCENT};
}

.progress {
    background-color: ${COLOR_DARK};
    border-radius: 4px;
}

.progressbar {
    background-color: ${COLOR_ACCENT};
    border-radius: 4px;
}

.button {
    background-color: ${COLOR_BORDER};
    border-radius: 4px;
    padding: 4px 8px;
}

.button:hover {
    background-color: ${COLOR_ACCENT};
}
EOF
